### ISSUE TITLE
define the scenario for using npx

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yajsapi#29]

**Comment by mdtanrikulu** [comment]
There are couple of scenarios we can actively use NPX; 

1. To generate Golem project template;
 - If a user wants to have an example implementation of yajsapi, user can simply call `npx yajsapi create <appName>`, so this will create a simple high level example of golem implementation project over yajsapi

2. To run quick scripts without having yajsapi installed;
- User can simply call any task script with calling yajsapi directly via npx instead of creating a project structure. Call can be something like; `npx yajsapi run <scriptPath>`

3. To run our tutorial examples without hosting github repository on users machine; 
- If user wants to see the tutorials without cloning our repo, they can call;
`npx yajsapi example blender <optional parameters>`

**Comment by shadeofblue** [comment]
possible duplicate: https://github.com/golemfactory/yagna-sdk-team/issues/72
