### ISSUE TITLE
UI - frontend SPA frame

### ISSUE THREAD

**Issue by mgordel** [golemfactory/yajsapi#387]

**Comment by Braunmann** [comment]
When looking for a front-end framework solution for an advanced example, two options were considered: Quasar and Nuxt:

**Quasar**
- a huge cobmo which gives you a lot out of the box which gives you blazing fast start without boilerplating
- but it's hard to swap out what's underneath or use another UI composer than provided.
- which makes the entry knowledge level seem much higher, e.g. I have to learn quasar vue components, specific solutions used in quasar
- it is cross-device
- not sure if it has a backend server built in to create APIs
-SSR, PWA, SPA

**Nuxt**
- lightweight, do not gives you so many built in components out of the box
- so you can pick and choose what's underneath, from UI components like Bootstrap, Tailwind, to feching lips like the axios library, native fetch, or authentication mechanisms like JWT, OAuth (both already approved and libraries from npm) etc.
- low threshold of entry, because you can use very popular libraries from npm, which practically everyone knows 
- it is not a cross device out of the box 
- it has a nice solution for setting up an API server, where you just write middleware for routers and it works 
- SSR, PWA, SPA

I have the impression that Quasar is more focused on providing UI Elements to be cross-device, and is only just early stage in support of frontend application development. 
Othewise Nuxt, is not a UI Component framework, it's a frontend Vue framework, not a set of Vue UI Componets. Helps support of development Vue frontend app that you can choose UI Component Set you like, and other lips for fetchng data, or auth. Give you routing and many helpers to create frontend app faster.  After fast boilerplating session, you can dive quickly in to crating Vue Component with bussiness logic.

**Comment by Braunmann** [comment]
The next consideration was the choice between the Nuxt v2 or v3 version and the rest of the stack.

Nuxt 2
 - Vue 2 only
 - Tailwind is avaliable
 - it is stable and mature 
 - good knowledge base on the internet
 - large community
 - We have internal team knowledge and we can develop faster

Nuxt 3 
 - Vue 3 (or Vue2)
 - Taiwind is avaliable
 - there is stable version from Nov 2022, but still is young
 - still a small community 
 - less known, there is no so big community like for v2 
 - we do not have internal knowledge and is different than v2, development process will be slower on the begining
 
In the type case, we considered the development time of the example vs the vision of the company. 

After long discussions with @mgordel  we decided on v3 because of the company vision to show that Golem uses modern but well known solutions. We would also like the example to last a long time and not to be quickly outdated. 

The stack we wold provide is:
- Nuxt 3
- Vue 3
- Tailwind
- Typescript
- Vite
